### ISSUE TITLE
wrong declaration of fileGetChar()

### ISSUE THREAD

**Issue by dromer** [pokitto/PokittoLib#16]
Here this empty function is declared as an int, while in the header it's set as a char.

https://github.com/pokitto/PokittoLib/blob/08e28c657a0f1d74549d4bdeba717995a5e8765c/Pokitto/POKITTO_LIBS/FileIO/FileIO_HW.cpp#L68
https://github.com/pokitto/PokittoLib/blob/08e28c657a0f1d74549d4bdeba717995a5e8765c/Pokitto/POKITTO_LIBS/FileIO/FileIO.h#L19

Which is it? :)

**Comment by pokitto** [comment]
Need to check. Too busy atm.

**Comment by Pharap** [comment]
`FileIO_SIM.cpp` has a functioning implementation that returns `char`,
so it's `FileIO_HW.cpp` that's at fault.
(So that answers the "Which is it?" part at least.)

---

The implementation is empty so I'm guessing this is either a library that hasn't been implemented for hardware yet or isn't supposed to be implemented for hardware.
